### PR TITLE
[JENKINS-35445] Custom HtmlUnit Dependency for JTH

### PR DESCRIPTION
**Pull request by andresrc**
See [JENKINS-35445](https://issues.jenkins-ci.org/browse/JENKINS-35445)

Downstream of https://github.com/andresrc/jenkins-test-harness-htmlunit/pull/1

### CODE REVIEW

**Comment by andresrc** [comment]
The upstream snapshot was not deployed, closing and reopening.

@reviewbybees

**Comment by andresrc** [comment]
@jenkinsci/code-reviewers Please see [JENKINS-35445](https://issues.jenkins-ci.org/browse/JENKINS-35445) and https://github.com/andresrc/jenkins-test-harness-htmlunit/issues/1

**Comment by olivergondza** [comment]
CCing @tfennelly who worked hard to get us back to upstream version. This seems to be a step back.

**Comment by jglick** [comment]
> back to upstream version. This seems to be a step back.

Well, this is not a fork of the sources. It only shades the classes from an official release.

**Comment by recena** [comment]
@olivergondza 

>  This seems to be a step back.

I don't think so. Now, at least, we are using an official version (ref. [JENKINS-31161](https://issues.jenkins-ci.org/browse/JENKINS-31161)).

👍 with this solution if we create a JIRA issue to solve the real problem.

**Comment by batmat** [comment]
Weak :+1:, IIUC https://github.com/andresrc/jenkins-test-harness-htmlunit is gonna need to get forked under jenkinsci right?
Then, when forked, we need to be careful of what happens there too to not waste Tom's work in the future, as rightly fears @olivergondza IMO.

**Comment by jglick** [comment]
:bee:

**Comment by andresrc** [comment]
@olivergondza @batmat when we need to upgrade `HtmlUnit` we just need to repackage it in the upstream jar. I've left version numbers that make it easy to map to the upstream project.

No `HtmlUnit` classes are transformed, just some of its transitive dependencies, which are the ones causing problems. In a next step I'll try to go for the xml libraries, which are also causing some problems (see https://github.com/jenkinsci/jenkins/pull/2404).

I'm going to merge and cut a release to pick it in the parent pom.

**Pull request merged**
