### PR TITLE
Stop swallowing exceptions that happen in `TestEnvironment#dispose()`

### PR DESCRIPTION
**Pull request by slonopotamus**
This commit is excepted to reveal bogus tests that do not properly shutdown,
especially on Windows where directory cannot be removed if there are any running processes that use it as a working directory.

### CODE REVIEW

**Comment by slonopotamus** [comment]
jenkinsci/git-plugin#798 is a nice case of a bug that was detected thanks to this PR + Windows CI.

**Comment by slonopotamus** [comment]
File descriptor leak in subversion plugin: jenkinsci/subversion-plugin#240
Technically, this is a MapDB bug that got fixed in later MapDB releases, but subversion plugin depended on ancient version.

**Comment by slonopotamus** [comment]
Attempt to upgrade to JTH with current fix discovered a bug in JTH itself: jenkinsci/workflow-cps-plugin#345 o_O

**Comment by slonopotamus** [comment]
Bug in workflow-support caused by dependency on old workflow-job: jenkinsci/workflow-support-plugin#99.

**Comment by slonopotamus** [comment]
Minor leaks in workflow-basic-steps-plugin tests: jenkinsci/workflow-basic-steps-plugin#103

**Comment by basil** [comment]
I filed PRs to update `pipeline-build-step`, `pipeline-githubnotify-step`, `pipeline-graph-analysis`, `pipeline-input-step`, `pipeline-milestone-step`, `pipeline-stage-step`, `pipeline-utility-steps`, `workflow-api`, and `workflow-cps-global-lib`. This exposed a few bugs in tests, which I fixed in jenkinsci/pipeline-graph-analysis-plugin#29, jenkinsci/pipeline-input-step-plugin#42, jenkinsci/pipeline-utility-steps-plugin#72, and jenkinsci/workflow-cps-global-lib-plugin#88.

**Comment by slonopotamus** [comment]
Cool! The only plugin that gives me headaches now is lockable-resources: jenkinsci/lockable-resources-plugin#170.

**Comment by MarkEWaite** [comment]
Thanks very much for enabling this setting and for fixing the bugs that it discovered in the git plugin.  Very much appreciated.

I was unwilling to wrestle further with the intermittent GitSCMTest and GitStatusTest build log related failures on ci.jenkins.io from this change.  I don't see those failures on the 5 Windows 10 machines that are in my local cluster.  Refer to https://github.com/jenkinsci/git-plugin/pull/802 for the workaround which adds a call to `JenkinsRule.waitUntilNoActivityUpTo()` into GitSCMTest when running on ci.jenkins.io and disables a few tests in GitStatusTest when running on ci.jenkins.io.

Thanks again for this change.  A very nice addition!

**Comment by slonopotamus** [comment]
WRT locks on build log: I'm not quite sure what's going on there. When working on workflow-support-plugin#99, I thought there's an issue in workflow-api/workflow-job plugin. But same solution didn't fix jenkinsci/lockable-resources-plugin#170. This needs more investigation. While sleeping for several seconds might allow tests to pass, I feel like this is just a way to hide a bug. My current understanding is that build log should not be accessed by anything after the build has finished.

**Pull request merged**
