### PR TITLE
Add a Spy for the SecurityListener

### PR DESCRIPTION
**Pull request by Wadeck**
- as requested in [#3074](https://github.com/jenkinsci/jenkins/pull/3074), the code is proposed in JTH to provide test helper for all plugins

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Not sure I understand the motivation for filing this. https://github.com/jenkinsci/jenkins/pull/3074 is not using it. If that were reworked to pick this up, _and_ there were some other PR (in a plugin) which could take advantage of it, then it would make sense.

**Comment by Wadeck** [comment]
@jglick each time the `SecurityListener` is used this helper class could be used to ease the related tests.
- [#22 in sshd](https://github.com/jenkinsci/sshd-module/pull/22)
- [#87 in github-oauth](https://github.com/jenkinsci/github-oauth-plugin/pull/87)
- all other plugin that want to test their usage of authentication events.

As we discussed about the `SecurityListener`, concerning the new abstract methods instead of the mini-design, this PR will be modified accordingly.

**Comment by jglick** [comment]
Putting on hold since it is not actually being used anywhere yet, so for now this is more of a prototype.

**Comment by Wadeck** [comment]
> Still something you want to do?

@jglick since that PR I haven't had to deal with this problem. I will close the PR for the moment.

**Pull request closed without merging**
