### PR TITLE
[JENKINS-41196] added alternate bootstrap logic

### PR DESCRIPTION
**Pull request by kohsuke**
With more servlets and filters initialized from within WebAppMain, test
harness needs to adjust as well.

This change is a pre-requisite of https://github.com/jenkinsci/jenkins/pull/2754

### CODE REVIEW

**Comment by kohsuke** [comment]
Anyone?

**Comment by kohsuke** [comment]
Trying magical @reviewbybees

**Comment by jglick** [comment]
Do not want to merge unless and until main PR is merged.

**Comment by jglick** [comment]
If a plugin expresses a dependency on a core component override plugin, does that actually work in its `JenkinsRule`-based tests? Did anyone try this?

**Comment by batmat** [comment]
Closing as stalled since 1+ year. Will be reopened when/if works on this is rebooted.

**Pull request closed without merging**
