### PR TITLE
[FIX JENKINS-34530] Make test harness work for 2.x based plugins

### PR DESCRIPTION
**Pull request by daniel-beck**
@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
Real diff: https://github.com/jenkinsci/jenkins-test-harness/pull/18/files?w=1

**Comment by jglick** [comment]
:bee:

**Comment by daniel-beck** [comment]
CC @olivergondza

**Comment by olivergondza** [comment]
LGTM

**Comment by andresrc** [comment]
:bee:

**Pull request merged**
