### PR TITLE
Use file-leak-detector to print open file handles when hitting IOExceptions

### PR DESCRIPTION
**Pull request by Vlatombe**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jglick** [comment]
This looks promising; is there a plan to file a mergeable version?

**Comment by Vlatombe** [comment]
I don't have so far, but could be if there is some traction. Possibly when file-leak-detector gets updated for java 11 and brought to jenkinsci org.

**Comment by jglick** [comment]
> when file-leak-detector gets updated for java 11

ref.: https://github.com/kohsuke/file-leak-detector/pull/48

**Comment by basil** [comment]
> Possibly when `file-leak-detector` gets updated for java 11 and brought to `jenkinsci` org.

[Done](https://github.com/jenkinsci/lib-file-leak-detector/releases/tag/file-leak-detector-1.14)

**Pull request closed without merging**
