### PR TITLE
Revert #544 so that `RealJenkinsRule` shuts down cleanly on Windows

### PR DESCRIPTION
**Pull request by dwnusbaum**
Based on CI build failures in https://github.com/jenkinsci/workflow-cps-plugin/pull/669 (see for example [this test output](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-669/5/testReport/org.jenkinsci.plugins.workflow.cps/CpsFlowDefinitionRJRTest/windows_11___Build__windows_11____flushLogsOnShutdown/)), I am suspicious that beyond the lack of shutdown-related log messages on older versions of Jenkins, https://github.com/jenkinsci/jenkins-test-harness/pull/544 might not shut down Jenkins cleanly on Windows, in particular I think `Jenkins.cleanUp` might not run and terminators may be skipped.

This PR injects an `ItemListener` dynamically into Jenkins using `ExtensionList.add` that writes a file in `onBeforeShutdown`, which is called by `Jenkins.cleanUp`, and after the restart we check for the existence of this file. Maybe there is something else we can already observe without needing this, but without `LoggerRule` I couldn't think of anything obvious.

`RealJenkinsRuleTest.restart` passes for me locally on MacOS with this PR.

EDIT: The tests confirmed my suspicions, so this PR now reverts #544 so that `RealJenkinsRule` shuts down cleanly on Windows.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dwnusbaum** [comment]
Hmm the CI build does fail on Windows but not on Linux. @jglick was https://github.com/jenkinsci/jenkins-test-harness/pull/544 necessary to fix an issue in some scenario, or was it just a simplification that could be reverted? As far as I can tell, that PR causes `RealJenkinsRule.stopJenkins` to not stop Jenkins cleanly on Windows, even when running Jenkins 2.391+.

**Comment by jglick** [comment]
It could be reverted I think, but I would like to know stopping the process does not cause terminators to run—if true, that certainly sounds like a bug?

**Comment by dwnusbaum** [comment]
> I would like to know why stopping the process does not cause terminators to run—if true, that certainly sounds like a bug?

Discussion in [JDK-4485742](https://bugs.openjdk.org/browse/JDK-4485742) and linked tickets indicates that `Process.destroy` terminates the process in a way that bypasses Java shutdown hooks on Windows, and that this will not be changed due to backwards compatibility implications. Looking at JDK source code, `ProcessHandle.destroy` seems to use the same native Windows API calls (compare [this](https://github.com/openjdk/jdk/blob/dfacda488bfbe2e11e8d607a6d08527710286982/src/java.base/windows/native/libjava/ProcessHandleImpl_win.c#L369) to [this](https://github.com/openjdk/jdk/blob/dfacda488bfbe2e11e8d607a6d08527710286982/src/java.base/windows/native/libjava/ProcessImpl_md.c#L454)), so I assume it has the same behavior.

**Comment by jglick** [comment]
Also [JDK-8056139](https://bugs.openjdk.org/browse/JDK-8056139). Hmm, that is unfortunate. We could fully revert #544, or continue to send SIGTERM on Linux and just use the special `/exit` endpoint on Windows.

**Comment by jglick** [comment]
> any reason to prefer `ProcessHandle.destroy`

Merely to avoid a gratuitous use of a different code path than what would often be used in a realistic context. I agree that having two modes is more confusing that it would be worth, so reverting #544 would be the simplest fix. Feel free to file that (it sounds like you already have some downstream work which would verify the effectiveness).

**Comment by dwnusbaum** [comment]
Ok, I push the revert to this PR. 

> it sounds like you already have some downstream work which would verify the effectiveness

I think the updates to `RealJenkinsRuleTest.restart` here are enough the validate the fix and prevent future regressions.

**Comment by jglick** [comment]
> the updates to `RealJenkinsRuleTest.restart` here are enough the validate the fix

You mean, when run on Windows.

**Review by jglick — APPROVED** [review]

**Comment by dwnusbaum** [comment]
> You mean, when run on Windows.

Yes, but the CI build here does test against Windows.

**Pull request merged**
