### PR TITLE
Forgot to specify source encoding

### PR DESCRIPTION
**Pull request by jglick**
Supersedes #5.

@reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
:bee:

**Comment by rsandell** [comment]
:bee:

**Comment by jtnord** [comment]
NBL do you also need the `project.reporting.outputEncoding` property so that javadoc is output in UTF-8 also?

**Comment by jglick** [comment]
> so that javadoc is output in UTF-8 also?

Could, if anyone complains about it I guess. This was the urgent one—uncompilable by some people without it.

**Pull request merged**
