### PR TITLE
[JENKINS-34496] Do not inject the plugin specific tests for things that are not plugins

### PR DESCRIPTION
**Pull request by stephenc**
- Requires supporting change in hpi plugin

@reviewbybees @jenkinsci/code-reviewers (esp @jglick @tfennelly)

See [JENKINS-34496](https://issues.jenkins-ci.org/browse/JENKINS-34496) and [my comment on previous attempt](https://github.com/jenkinsci/maven-hpi-plugin/pull/32#issuecomment-235213727)

Linked PR against maven-hpi-plugin to follow

### CODE REVIEW

**Comment by andresrc** [comment]
:bee:

**Comment by amuniz** [comment]
:bee:

**Comment by tfennelly** [comment]
🐝

**Comment by stephenc** [comment]
@reviewbybees done

**Pull request merged**
